#!/usr/bin/env Rscript

# Script to merge mulitple functional profiles from different directories which were generated by pnnl-atlas for metageonomic result
# Warning, this script works in linux, for window the slash in path is different
# Sizhong Yang, 2018-2-13, Potsdam


mergeProfiles <- function(input_dir, output_dir, samples, mergeby = c('EC_number','product'), sep = "\t", extention = 'tsv', unassigned = 'unnamed', file='merged_functionprofile.tsv', ...){
    message('This function was designed for structured annotation result produced by pnnl-atlas')
   # read in data  
  input_dir <- gsub("\\/$","",input_dir)
  output_dir <- gsub("\\/$","",output_dir)
   paths = paste0(input_dir,'/',samples,'/',samples,'_annotations.txt')
   datalist = lapply(paths, function(x) read.table(file = x, 
        header = T, sep = "\t", fill = T, quote="",encoding = 'utf-8'))
    # quote is necessary to escape EOF within quoted string
    # aggregate each tabel first
   myformula = as.formula(paste('count', paste(mergeby,collapse="+"), sep =" ~ "))
   datalist2 = lapply(datalist, function(x) aggregate(myformula, data = x, sum))
   # merge multiple functional df toghter
   oldw <- getOption("warn")
   options(warn = -1)
   result = Reduce(function(x,y){merge(x, y, by = mergeby,all = T)}, datalist2)
   result[is.na(result)] <- 0  # replace NA with zero
   result$EC_number =  sub('^$', unassigned, result$EC_number)
   start = length(mergeby) + 1 # merged courts from the column after the bywhat
   end = ncol(result)
   names(result)[start:end] = samples
    # write table out
   extent = extention
   if(sep == ',') extent ='csv'
   else if(sep == '\t') extent
   else  {extent = 'tsv'
         warning('We only accept seperation of comma or tab')}
   filenm = ifelse(grepl("\\.txt$|\\.tsv$|\\.csv$",file), file, paste0(file,'.',extent)) 
   print(filenm)
   outpath = paste0(output_dir,'/',filenm)
   write.table(result, file= outpath, quote = F, sep = sep, ...)
   options(warn = oldw)
   message(paste("Please check the result in folder", output_dir))
   message('Enjoy your result!')
   return(result)
}  # end of the function

# ----------------------------------
# example to use function
# ----------------------------------

hin =  "yourpath_input"
hout = "yourpath_output"
samples=c('sample1','sample2','sample3','sample3','sample5','sample5')
res = mergeProfiles(input_dir = hin,output_dir = hout,samples=samples, mergeby=c('EC_number','product'),file='test.tsv')
res_sorted = res[order(rowSums(res[,3:8]),decreasing=T), ]
head(res_sorted, 20)